# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "17:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "org.apache.tomcat:tomcat-catalina"
        versions: ["[10.0,)"]
      - dependency-name: "org.mockito:mockito-core"
        versions: ["[5.0,)"]
      - dependency-name: "org.mockito:mockito-junit-jupiter"
        versions: ["[5.0,)"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "17:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 100
