name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      additionalGradleOptions:
        description: 'Additional Gradle options'
        required: false
        default: ''

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: 'build ${{ github.event.inputs.additionalGradleOptions }}'

    - name: Upload reports
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: reports
        path: build/reports
        retention-days: 3

    - name: Upload libs
      uses: actions/upload-artifact@v3
      with:
        name: libs
        path: build/libs
        retention-days: 3

    - name: Upload docs
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: build/docs
        retention-days: 3
